import {
    Layers as ArticleGenerator,
    Shuffle as RewriteArticle,
    Tag as TagsGenerator,
    Clipboard as NameGenerator,
    Code as CodeGenerator,
    ColorPalette as ImageGenerator,
    DonutChart as AdsContent,
    Film as VideoScript,
    Internet as GrammarChecker,
    LeftAlign as WriteDescription,
    Message as AIChatBot,
    Sort as WriteTitle,
} from "../components/icons";

export const projects = [
    {
        id: "CT24P00123456",
        icon: <ArticleGenerator />,
        link: "/app/project/0001",
        slug: "article-generator",
        name: "TEST Dianne Kochol",
        address: "500 Moss Farms Road, Cheshire, CT 06410",
        phone: "203-555-5555",
        status: "active",
        prompt: "TEST Dianne Kochol",
        api: "Text",
        aimodel: "davinci",
        description:
            "First Site Visit",
        progress: 0.5,
        assessment_date: "August 29, 2024",
    },
    {
        id: "CT24P0012355",
        icon: <ArticleGenerator />,
        link: "/app/project/0002",
        slug: "article-generator",
        name: "Test Project 2",
        address: "12345 Main Street, Hartford, CT 06111",
        phone: "203-555-5555",
        status: "active",
        prompt: "Test Project 2",
        api: "Text",
        aimodel: "davinci",
        description:
            "First Site Visit with Barrier",
        progress: 0.3,
        assessment_date: "September 4, 2024",
    },
    {
        id: "CT24P00123466",
        icon: <ArticleGenerator />,
        link: "/app/project/0003",
        slug: "article-generator",
        name: "Test Project 3",
        address: "12345 Main Street, New Haven, CT 06111",
        phone: "203-555-5555",
        status: "active",
        prompt: "Test Project 3",
        api: "Text",
        aimodel: "davinci",
        description:
            "First Site Visit",
        progress: 0.0,
        assessment_date: "September 5, 2024",
    },
    {
        id: "CT24P00123488",
        icon: <ArticleGenerator />,
        link: "/app/project/0004",
        slug: "article-generator",
        name: "Test Project 4",
        address: "123 Main Street, Trumbull, CT 06111",
        phone: "203-555-5555",
        status: "active",
        prompt: "Test Project 4",
        api: "Text",
        aimodel: "davinci",
        description:
            "First Site Visit",
        progress: 0.0,
        assessment_date: "September 5, 2024",
    },
    {
        id: "CT24P00123499",
        icon: <ArticleGenerator />,
        link: "/app/project/0005",
        slug: "article-generator",
        name: "Test Project 3",
        address: "126 Main Street, Norwalk, CT 06111",
        phone: "203-555-5555",
        status: "active",
        prompt: "Test Project 5",
        api: "Text",
        aimodel: "davinci",
        description:
            "First Site Visit",
        progress: 0.0,
        assessment_date: "September 6, 2024",
    },
    {
        id: "CT24P00123433",
        icon: <ArticleGenerator />,
        link: "/app/project/0006",
        slug: "article-generator",
        name: "Test Project 6",
        address: "4456 Main Street, Bristol, CT 06111",
        phone: "203-555-5555",
        status: "active",
        prompt: "Test Project 6",
        api: "Text",
        aimodel: "davinci",
        description:
            "First Site Visit",
        progress: 0.0,
        assessment_date: "September 6, 2024",
    },    
    
];

